POST http://localhost:3000/api/auth
content-type: application/json

{
  "email": "Jason@gmail.com",
  "password": "Jasonpassword"
}

###
POST http://localhost:3000/api/auth
content-type: application/json

{
  "email": "folmokelte@vusra.com",
  "password": "test"
}

###
POST http://localhost:3000/api/auth
content-type: application/json

{
  "email": "Kyle@gmail.com",
  "password": "Kylepassword"
}

###
POST http://localhost:3000/api/auth
content-type: application/json

{
  "email": "Rose@gmail.com",
  "password": "Rosepassword"
}

###
POST http://localhost:3000/api/auth
content-type: application/json

{
  "email": "HuKai@gmail.com",
  "password": "HuKaipassword"
}

###
POST http://localhost:3000/api/auth
content-type: application/json

{
  "email": "cudrisalmu@vusra.com",
  "password": "Alicepassword"
}


// -------------------------------- is Admin ----------------------

###
POST http://localhost:3000/api/auth/isAdmin
content-type: application/json

{
  "email": "Jason@gmail.com",
  "password": "Jasonpassword"
}

###
POST http://localhost:3000/api/auth/isAdmin
content-type: application/json

{
  "email": "HuKai@gmail.com",
  "password": "HuKaipassword"
}

###
POST http://localhost:3000/api/auth/isAdmin
content-type: application/json

{
  "email": "Kyle@gmail.com",
  "password": "Kylepassword"
}