POST http://localhost:8080/store/cartItems
Content-Type: application/json

{
  "productId": "619fd4816d78a846c04fce78"
}

###
POST http://localhost:8080/store/cartItems
Content-Type: application/json

{
  "productId": "619fd4886d78a846c04fce7c",
  "number": 2
}

###
POST http://localhost:8080/store/cartItems
Content-Type: application/json

{
  "productId": "619fd4836d78a846c04fce7a",
  "number": 10
}

###
GET http://localhost:8080/store/cartItems

###
GET http://localhost:8080/store/cartItems/619fd4f99c14722cd88acd43

###
PATCH  http://localhost:8080/store/cartItems/619fd4f99c14722cd88acd43
Content-Type: application/json

{
  "number": 2
}

###
DELETE http://localhost:8080/store/cartItems/619fdb3d07df633ffc68ffe8