POST http://localhost:3000/api/orders/createOrder
content-type: application/json

{
  "totalPrice": 200,
  "timestamp": "2022-4-6",
  "customerEmail": "Jason@gmail.com",
  "purchasedItems": [
    {
      "imageUrl": "https://fakestoreapi.com/img/71kWymZ+c+L._AC_SX679_.jpg",
      "quantity": 2,
      "productName": "Silicon Power 256GB SSD 3D NAND A55 SLC Cache Performance Boost SATA III 2.5",
      "productId": "61e4b81af187b721109e2080",
      "price": 200,
      "ownerEmail": "Rose@gmail.com"
    }
  ]
}

###
POST http://localhost:3000/api/orders/createOrder
content-type: application/json

{
  "totalPrice": 300,
  "timestamp": "2022-4-6",
  "customerEmail": "HuKai@gmail.com",
  "purchasedItems": [
    {
      "imageUrl": "https://fakestoreapi.com/img/71kWymZ+c+L._AC_SX679_.jpg",
      "quantity": 2,
      "productName": "Silicon Power 256GB SSD 3D NAND A55 SLC Cache Performance Boost SATA III 2.5",
      "productId": "61e4b81af187b721109e2080",
      "price": 200,
      "ownerEmail": "Rose@gmail.com"
    }
  ]
}

###
GET http://localhost:3000/api/orders/getOrders
content-type: application/json

{
  "customerEmail": "HuKai@gmail.com"
}