GET http://localhost:3000/api/orders/getOrders

###
POST http://localhost:3000/api/orders/createOrder
content-type: application/json

{
  "totalPrice": 200,
  "timestamp": "2022-4-6",
  "customerEmail": "Jason@gmail.com",
  "purchasedItems": [
    {
      "imageUrl": "https://fakestoreapi.com/img/71kWymZ+c+L._AC_SX679_.jpg",
      "quantity": 2,
      "productName": "Silicon Power 256GB SSD 3D NAND A55 SLC Cache Performance Boost SATA III 2.5",
      "productId": "61e4b81af187b721109e2080",
      "price": 200,
      "ownerEmail": "Rose@gmail.com"
    }
  ],
  "billingInfo": {
    "fullName": "Huang Lingxiao",
    "country": "Finland",
    "streetAddress": "Fake street 123",
    "phoneNumber": "555-555-555",
    "postalCode": "114514",
    "city": "Helsinki",
    "paymentMethod": "PayPal"
  }
}

###
POST http://localhost:3000/api/orders/createOrder
content-type: application/json

{
  "totalPrice": 300,
  "timestamp": "2022-4-6",
  "customerEmail": "HuKai@gmail.com",
  "purchasedItems": [
    {
      "imageUrl": "https://fakestoreapi.com/img/71kWymZ+c+L._AC_SX679_.jpg",
      "quantity": 2,
      "productName": "Silicon Power 256GB SSD 3D NAND A55 SLC Cache Performance Boost SATA III 2.5",
      "productId": "61e4b81af187b721109e2080",
      "price": 200,
      "ownerEmail": "Rose@gmail.com"
    }
  ],
  "billingInfo": {
    "fullName": "Hu Kai",
    "country": "Finland",
    "streetAddress": "Fake street 123",
    "phoneNumber": "114-514-1919810",
    "postalCode": "114514",
    "city": "Helsinki",
    "paymentMethod": "Google Pay"
  }
}

###
GET http://localhost:3000/api/orders/getOrders/Jason@gmail.com

###
DELETE http://localhost:3000/api/orders/deleteOrder
content-type: application/json

{
  "orderId": "624f00e1b8df3900220bf42b"
}