###
POST http://localhost:3000/api/products
content-type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MWE4ZDE1MzJmZGEyNzNkYTg4NGE1NWQiLCJpYXQiOjE2Mzg0ODM0MDF9.ZcHNp1UYz6-mw3O3-QzN6K03tmxD6_IfZly8OFsjMEs

// not completed, should also include imageUrl and description

{
  "name": "laptop",
  "price": "1000",
  "genre": "electronic",
  "numberInStock": 20,
  "ownerEmail": "Jason@gmail.com"
}

###
POST http://localhost:3000/api/products
content-type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MWE4ZDE1MzJmZGEyNzNkYTg4NGE1NWQiLCJpYXQiOjE2Mzg0ODM0MDF9.ZcHNp1UYz6-mw3O3-QzN6K03tmxD6_IfZly8OFsjMEs

{
  "name": "desktop",
  "price": "2000",
  "genre": "electronic",
  "numberInStock": 10,
  "ownerEmail": "HuKai@gmail.com"
}


###
POST http://localhost:3000/api/products
content-type: application/json

{
  "name": "router",
  "price": "50",
  "genre": "electronic",
  "numberInStock": 50
}

###
POST http://localhost:3000/api/products
Content-Type: application/json

{
  "name": "desktop",
  "price": "2000",
  "genre": "electronic",
  "numberInStock": 15
}


###
GET http://localhost:3000/api/products

###
GET http://localhost:3000/api/products/619aa9a664644257408d9fab

###
PUT http://localhost:3000/api/products/619a9b7a26bb485578bd865e
Content-Type: application/json

{
  "name": "mobile phone",
  "price": "1000",
  "genre": "electronic",
  "numberInStock": 40
}

###
DELETE  http://localhost:3000/api/products/61a7e70668794f46605862a0
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MWU0YjdmMmYxODdiNzIxMTA5ZTIwMmYiLCJpYXQiOjE2NTAzNjM1MjZ9.M5X_hGIU9hr2wjYg2212For0lNHiMt1fHEJf6duaoks