GET http://localhost:3000/api/user

###
POST http://localhost:3000/api/user
content-type: application/json

{
  "name": "Lisa",
  "email": "Lisa@gmail.com",
  "password": "Lisapassword"
}

###
GET http://localhost:3000/api/user/me
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MWU0YjdmMmYxODdiNzIxMTA5ZTIwMmYiLCJpYXQiOjE2NDI5MDU1Mjd9.EQZERK7w9W57uX741ylpx1i5uAiVeSbTgEDjcaKOJI4

###
GET http://localhost:3000/api/user/me
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MWE5Mzc3OTZiYjg0ODM2MTA3NTNkNTciLCJpYXQiOjE2MzkyNDMzOTJ9.wvCPqLl8IhPBNX1E5OWO5_1Y9QEeEEkK00wV7MuSwZ4

###
PATCH http://localhost:3000/api/user/61a8ba75f77ec64d9c676d9d
content-type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MWE5Mzc3OTZiYjg0ODM2MTA3NTNkNTciLCJpYXQiOjE2Mzg0ODc2NTh9.FV1rFmjoW9da4FlPrfqpiJFaLY06jpL-HEZdl64vVn8

{
  "email": "HuKai@outlook.com"
}

### ------------------------------------------ add cart items -----------------------------------------------------
PATCH http://localhost:3000/api/user/cart/add
content-type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MWI2Njk4MDEwODQ2MzE3ZjAzODgxM2EiLCJpYXQiOjE2MzkzNDQ2MjN9.ueo0j79cn9ujx1U4bluESjckXfLU0ErFcV5UkZqoGXo

{
  "email": "Jason@gmail.com",
  "productId": "61e4b81af187b721109e2080"
}

###
PATCH http://localhost:3000/api/user/cart/add
content-type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MWI2Njk4MDEwODQ2MzE3ZjAzODgxM2EiLCJpYXQiOjE2MzkzNDQ2MjN9.ueo0j79cn9ujx1U4bluESjckXfLU0ErFcV5UkZqoGXo

{
  "email": "HuKai@gmail.com",
  "productId": "61e4b7faf187b721109e203c"
}

###
PATCH http://localhost:3000/api/user/cart/add
content-type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MWI2Njk4MzEwODQ2MzE3ZjAzODgxM2QiLCJpYXQiOjE2MzkzNDQ2OTR9.0z9B2RZkxI3dF_phQxBOEw279DvyEBSGKXk-ZimG6FI

{
  "email": "HuKai@gmail.com",
  "productName": "SanDisk SSD PLUS 1TB Internal SSD - SATA III 6 Gb/s",
  "quantity": 1
}

###
PATCH http://localhost:3000/api/user/cart/add
content-type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MWI2Njk4MzEwODQ2MzE3ZjAzODgxM2QiLCJpYXQiOjE2MzkzNDQ2OTR9.0z9B2RZkxI3dF_phQxBOEw279DvyEBSGKXk-ZimG6FI

{
  "email": "Kyle@gmail.com",
  "productName": "Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops",
  "quantity": 10
}

### ---------------------------------- Modify, Increment, decrement, delete and clear cart item --------------------------------
###
PATCH http://localhost:3000/api/user/cart/modify
content-type: application/json

{
  "email": "Rose@gmail.com",
  "itemId": "620128ee70c5a40022acb1b4",
  "quantity": 5
}

###
PATCH http://localhost:3000/api/user/cart/increment
content-type: application/json

{
  "email": "Jason@gmail.com",
  "itemId": "61bcfb49c1bdab508cc13e21"
}

###
PATCH http://localhost:3000/api/user/cart/decrement
content-type: application/json

{
  "email": "Jason@gmail.com",
  "itemId": "61bcfb49c1bdab508cc13e21"
}

###
PATCH http://localhost:3000/api/user/cart/delete
content-type: application/json

{
  "email": "Jason@gmail.com",
  "itemId": "61bcfb49c1bdab508cc13e21"
}

###
PATCH http://localhost:3000/api/user/cart/clear
content-type: application/json

{
  "email": "Kyle@gmail.com"
}

### ---------------------------------- Add, delete and update listings -------------------------------------------------------------
PATCH http://localhost:3000/api/user/listing/add
content-type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MWI2Njk4MzEwODQ2MzE3ZjAzODgxM2QiLCJpYXQiOjE2MzkzNDQ2OTR9.0z9B2RZkxI3dF_phQxBOEw279DvyEBSGKXk-ZimG6FI

{
  "product": {
    "imageUrl": "https://www.someimage.com",
    "name": "Asus VivoBook S16",
    "price": 1600,
    "description": "best lightweight laptop of Asus",
    "numberInStock": 1,
    "genre": "electronic",
    "ownerEmail": "Jason@gmail.com"
  }
}

###
PATCH http://localhost:3000/api/user/listing/update
content-type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MWI2Njk4MzEwODQ2MzE3ZjAzODgxM2QiLCJpYXQiOjE2MzkzNDQ2OTR9.0z9B2RZkxI3dF_phQxBOEw279DvyEBSGKXk-ZimG6FI

{
  "productId": "61beec3f50c89937dcb43651",
  "update": {
    "price": 1500,
    "numberInStock": 10
  },
  "email": "Jason@gmail.com"
}

###
DELETE http://localhost:3000/api/user/listing/delete
content-type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MWI2Njk4MzEwODQ2MzE3ZjAzODgxM2QiLCJpYXQiOjE2MzkzNDQ2OTR9.0z9B2RZkxI3dF_phQxBOEw279DvyEBSGKXk-ZimG6FI

{
  "productId": "61be1083c2baf427a008a8a2",
  "email": "Kyle@gmail.com"
}

###
DELETE http://localhost:3000/api/user/61a937746bb8483610753d54
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MWE5Mzc3OTZiYjg0ODM2MTA3NTNkNTciLCJpYXQiOjE2MzkyMzg0MzB9.SOS0nnqTB0EDTYZvctbd2BrlfR9t7apf_F317ws0gXI