GET http://localhost:3000/api/user

###
GET http://localhost:3000/api/user/me
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MWE4ZDE1MzJmZGEyNzNkYTg4NGE1NWQiLCJpYXQiOjE2Mzg0ODcxMjF9.lSTYRpzxMZ_7vk1V29HhN89lrXBf3EVdKoS_WwJOB40

###
GET http://localhost:3000/api/user/me
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MWE5Mzc3OTZiYjg0ODM2MTA3NTNkNTciLCJpYXQiOjE2MzkyNDMzOTJ9.wvCPqLl8IhPBNX1E5OWO5_1Y9QEeEEkK00wV7MuSwZ4

###
PATCH http://localhost:3000/api/user/61a8ba75f77ec64d9c676d9d
content-type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MWE5Mzc3OTZiYjg0ODM2MTA3NTNkNTciLCJpYXQiOjE2Mzg0ODc2NTh9.FV1rFmjoW9da4FlPrfqpiJFaLY06jpL-HEZdl64vVn8

{
  "email": "HuKai@outlook.com"
}

###
POST http://localhost:3000/api/user
content-type: application/json

{
  "name": "Jason",
  "email": "Jason@gmail.com",
  "password": "Jasonpassword"
}

###
POST http://localhost:3000/api/user
content-type: application/json

{
  "name": "HuKai",
  "email": "HuKai@gmail.com",
  "password": "HuKaipassword"
}

###
POST http://localhost:3000/api/user
content-type: application/json

{
  "name": "Kyle",
  "email": "Kyle@gmail.com",
  "password": "Kylepassword"
}

###
POST http://localhost:3000/api/user
content-type: application/json

{
  "name": "Rose",
  "email": "Rose@gmail.com",
  "password": "Rosepassword"
}

###
PATCH http://localhost:3000/api/user
content-type: application/json

{
  "email": "Jason@gmail.com",
  "productName": "Solid Gold Petite Micropave",
  "quantity": 1
}

###
PATCH http://localhost:3000/api/user
content-type: application/json

{
  "email": "Jason@gmail.com",
  "productName": "Mens Cotton Jacket",
  "quantity": 2
}

###
PATCH http://localhost:3000/api/user
content-type: application/json

{
  "email": "HuKai@gmail.com",
  "productName": "SanDisk SSD PLUS 1TB Internal SSD - SATA III 6 Gb/s",
  "quantity": 2
}

###
PATCH http://localhost:3000/api/user
content-type: application/json

{
  "email": "Kyle@gmail.com",
  "productName": "Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops",
  "quantity": 10
}

###
DELETE http://localhost:3000/api/user/61a937746bb8483610753d54
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MWE5Mzc3OTZiYjg0ODM2MTA3NTNkNTciLCJpYXQiOjE2MzkyMzg0MzB9.SOS0nnqTB0EDTYZvctbd2BrlfR9t7apf_F317ws0gXI