POST http://localhost:3000/store/user
content-type: application/json

{
  "name": "Jason",
  "email": "Jason@gmail.com",
  "password": "Jasonpassword"
}

###
POST http://localhost:3000/store/user
content-type: application/json

{
  "name": "HuKai",
  "email": "HuKai@gmail.com",
  "password": "HuKaipassword"
}

###
POST http://localhost:3000/store/user
content-type: application/json

{
  "name": "Kyle",
  "email": "Kyle@gmail.com",
  "password": "Kylepassword"
}

###
POST http://localhost:3000/store/user
content-type: application/json

{
  "name": "Rose",
  "email": "Rose@gmail.com",
  "password": "Rosepassword"
}

###
PATCH http://localhost:3000/store/user
content-type: application/json

{
  "email": "Jason@gmail.com",
  "productName": "Solid Gold Petite Micropave",
  "quantity": 1
}

###
PATCH http://localhost:3000/store/user
content-type: application/json

{
  "email": "Jason@gmail.com",
  "productName": "Mens Cotton Jacket",
  "quantity": 2
}

###
PATCH http://localhost:3000/store/user
content-type: application/json

{
  "email": "HuKai@gmail.com",
  "productName": "SanDisk SSD PLUS 1TB Internal SSD - SATA III 6 Gb/s",
  "quantity": 2
}